//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АбонентыEntities : DbContext
    {
        private static АбонентыEntities _context;
        public АбонентыEntities()
            : base("name=АбонентыEntities")
        {
        }
        public static АбонентыEntities GetContext()
        {
            if (_context == null)
                _context = new АбонентыEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Абоненты> Абоненты { get; set; }
        public DbSet<Разговоры> Разговоры { get; set; }
        public DbSet<Тарифы> Тарифы { get; set; }
        public DbSet<Телефоны> Телефоны { get; set; }
    }
}
