//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абоненты
    {
        public Абоненты()
        {
            this.Телефоны = new HashSet<Телефоны>();
        }
    
        public int IDАбонента { get; set; }
        public Nullable<int> Номер_Абонента { get; set; }
        public string ФИО_абонента { get; set; }
        public string Адрес { get; set; }
    
        public virtual ICollection<Телефоны> Телефоны { get; set; }
    }
}
