//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разговоры
    {
        public int idРазговора { get; set; }
        public Nullable<int> Номер_Разговора { get; set; }
        public Nullable<System.DateTime> Дата_Разговора { get; set; }
        public Nullable<int> Продолжительность { get; set; }
        public Nullable<int> idТарифа { get; set; }
        public Nullable<int> idТелефона { get; set; }
    
        public virtual Тарифы Тарифы { get; set; }
        public virtual Телефоны Телефоны { get; set; }
    }
}
